inherits:
  - strictness_low

ignore-patterns:
  - (^|/)\..+
  - ^docs/
  - ^build/

test-warnings: true

output-format: grouped

dodgy:
    run: true

mccabe:
    run: false

pep257:
    run: false

pep8:
    run: true
    options:
        max-line-length: 100

pyflakes:
    run: true

pylint:
    run: true
    options:
        max-line-length: 80
        const-rgx: "(([A-Z_][A-Z0-9_]*)|(__.*__)|log)$"
        const-hint: "(([A-Z_][A-Z0-9_]*)|(__.*__)|log)$"
        ignored-classes: pytest
    disable:
        - C0302
        - W0142
        - W0141
